[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.34"

[features]
resolution = true
skip-lint = false

[programs.devnet]
position = "GMCkSz2KK2oS7aiBMsLmHNXCoN97YriUXBy2Q1EFFVad"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"
