[toolchain]
anchor_version = "0.30.1"
solana_version = "2.1.6"

[features]
resolution = true
skip-lint = false

[programs.devnet]
position = "Dk1TMwYtjVEEZsovJrtun34hae6Vw1mqhFMjgZ8zkmQ7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"
