[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
position = "KmEz82PFdFmBxUYSatKKggE64MVWrzXK26K7utCgndz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
